#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Supermarket.Model;

namespace Supermarket.Model	
{
	public partial class Vendor
	{
		private int id;
		public virtual int Id
		{
			get
			{
				return this.id;
			}
			set
			{
				this.id = value;
			}
		}
		
		private string vendorName;
		public virtual string VendorName
		{
			get
			{
				return this.vendorName;
			}
			set
			{
				this.vendorName = value;
			}
		}
		
		private IList<Product> products = new List<Product>();
		public virtual IList<Product> Products
		{
			get
			{
				return this.products;
			}
		}
		
	}
}
#pragma warning restore 1591
